sudo: false

language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install

script:
  - vendor/bin/codecept build -c codeception.yml
  - vendor/bin/codecept run -c codeception.yml -f
